name: Python CI/CD

on:
  push:
    branches:
      - main  # or replace with 'master' if your default branch is named 'master'
  pull_request:
    branches:
      - main  # or replace with 'master' if your default branch is named 'master'

jobs:
  install:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install matplotlib

      - name: Set Status Badge
        run: |
          echo "Install Status: ${{ job.status }}" >> README.md
          echo "<img src='https://github.com/actions-badge/badge/v1/status/${{ github.repository }}/${{ github.workflow }}-${{ github.run_id }}/install' alt='Install Status Badge' />" >> README.md

  lint:

    runs-on: ubuntu-latest

    needs: install

    steps:
      - uses: actions/checkout@v2

      - name: Set Status Badge
        run: |
          echo "Lint Status: ${{ job.status }}" >> README.md
          echo "<img src='https://github.com/actions-badge/badge/v1/status/${{ github.repository }}/${{ github.workflow }}-${{ github.run_id }}/lint' alt='Lint Status Badge' />" >> README.md

  format:

    runs-on: ubuntu-latest

    needs: lint

    steps:
      - uses: actions/checkout@v2

      - name: Set Status Badge
        run: |
          echo "Format Status: ${{ job.status }}" >> README.md
          echo "<img src='https://github.com/actions-badge/badge/v1/status/${{ github.repository }}/${{ github.workflow }}-${{ github.run_id }}/format' alt='Format Status Badge' />" >> README.md

  test:

    runs-on: ubuntu-latest

    needs: format

    steps:
      - uses: actions/checkout@v2

      - name: Run Tests
        run: |
          python -m unittest tests.test_main

      - name: Set Status Badge
        run: |
          echo "Test Status: ${{ job.status }}" >> README.md
          echo "<img src='https://github.com/actions-badge/badge/v1/status/${{ github.repository }}/${{ github.workflow }}-${{ github.run_id }}/test' alt='Test Status Badge' />" >> README.md
